// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ2m7O-D5O53pMMKs5FWqkLQiHwPGMRxM',
    appId: '1:712766615245:web:7c27a68c28debe4d03c384',
    messagingSenderId: '712766615245',
    projectId: 'ecomerce-cfffd',
    authDomain: 'ecomerce-cfffd.firebaseapp.com',
    storageBucket: 'ecomerce-cfffd.appspot.com',
    measurementId: 'G-N75T09MHDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjaE1vAJKZFv0v_V07LaW32VIcpkyKluk',
    appId: '1:712766615245:android:e9b8c07c7b31104503c384',
    messagingSenderId: '712766615245',
    projectId: 'ecomerce-cfffd',
    storageBucket: 'ecomerce-cfffd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkZwdH4m9Lx_nzKT8JrrCIMUzeU-fCr2k',
    appId: '1:712766615245:ios:c2ede837af9a7ac803c384',
    messagingSenderId: '712766615245',
    projectId: 'ecomerce-cfffd',
    storageBucket: 'ecomerce-cfffd.appspot.com',
    iosClientId: '712766615245-v84rin2vddinbqh23d71bsrgnmeu4ipp.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomerceFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkZwdH4m9Lx_nzKT8JrrCIMUzeU-fCr2k',
    appId: '1:712766615245:ios:883e7959d2df27e903c384',
    messagingSenderId: '712766615245',
    projectId: 'ecomerce-cfffd',
    storageBucket: 'ecomerce-cfffd.appspot.com',
    iosClientId: '712766615245-lek61jk7nbqtj2evghlr5u5ehn6e1qho.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomerceFlutter.RunnerTests',
  );
}
